#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BCMWebApp.Droid.Resource", IsApplication=true)]

namespace BCMWebApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonBorder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int noBorder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int normalBlueBorder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int normalBorder = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int normalRedBorder = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int normalWhiteBorder = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int ContentLayout = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int PasswordLabel = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int botLogin = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int etPassword = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int etUsuario = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int frameLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int gridEmpresas = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int linearLayoutPassword = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int linearLayoutTitle = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int linearLayoutUsuario = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int tvGeneralErrorLabel = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int tvPasswordErrorLabel = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int tvTitle = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int tvUsuarioErrorLabel = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int tvUsuarioLabel = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Empresas = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ErrorConexion = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int emailInvalid = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int emailRequired = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int loginError1 = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int passwordRequired = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
