INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,1,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,2,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,3,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,4,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,5,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,6,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,7,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,8,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,9,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,10,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,11,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,12,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,13,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,14,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,15,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,16,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,17,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,18,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,19,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,20,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,21,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,22,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,23,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,24,1);
INSERT INTO [dbo].[tblCiudad] ([IdPais], [IdEstado], [IdCiudad]) VALUES (1,25,1);

INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,1,1,'Puerto Ayacucho');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,2,1,'Barcelona');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,3,1,'San Fernando de Apure');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,4,1,'Maracay');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,5,1,'Barinas');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,6,1,'Ciudad Bolívar');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,7,1,'Valencia');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,8,1,'San Carlos');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,9,1,'Tucupita');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,10,1,'Caracas');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,11,1,'Coro');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,12,1,'San Juan de los Morros');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,13,1,'La Guaira');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,14,1,'Barquisimeto');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,15,1,'Mérida');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,16,1,'Los Teques');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,17,1,'Maturín');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,18,1,'La Asunción');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,19,1,'Guanare');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,20,1,'Cumaná');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,21,1,'San Cristobal');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,22,1,'Trujillo');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,23,1,'San Felipe');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,24,1,'Maracaibo');
INSERT INTO [dbo].[tblCultura_Ciudad] ([Culture], [IdPais], [IdEstado], [IdCiudad], [Nombre]) VALUES ('es-VE',1,25,1,'Los Roques');
