INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,1);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,2);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,3);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,4);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,5);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,6);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,7);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,8);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,9);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,10);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,11);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,12);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,13);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,14);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,15);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,16);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,17);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,18);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,19);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,20);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,21);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,22);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,23);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,24);
INSERT INTO [dbo].[tblEstado] ([IdPais],[IdEstado]) VALUES(1,25);

INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,1,'Amazonas');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,2,'Anzoátegui');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,3,'Apure');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,4,'Aragua');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,5,'Barinas');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,6,'Bolivar');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,7,'Carabobo');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,8,'Cojedes');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,9,'Delta Amacuro');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,10,'Distrito Capital');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,11,'Falcón');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,12,'Guárico');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,13,'La Guaira');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,14,'Lara');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,15,'Mérida');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,16,'Miranda');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,17,'Monagas');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,18,'Nueva Esparta');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,19,'Portuguesa');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,20,'Sucre');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,21,'Táchira');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,22,'Trujillo');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,23,'Yaracuy');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,24,'Zulia');
INSERT INTO [dbo].[tblCultura_Estado] ([Culture], [IdPais], [IdEstado], [Nombre]) VALUES('es-VE',1,25,'Dependencias Federales');
