//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuditoriaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditoriaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCMWeb.App_LocalResources.AuditoriaResource", typeof(AuditoriaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir documento {1} versión {2} del módulo {0}.
        /// </summary>
        public static string AbrirDocumentoMessage {
            get {
                return ResourceManager.GetString("AbrirDocumentoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir el archivo PDF del documento {1} versión {2} desde un dispositivo móvil.
        /// </summary>
        public static string AbrirPDFMovilMessage {
            get {
                return ResourceManager.GetString("AbrirPDFMovilMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir el archivo PDF del documento {1} versión {2} desde un pc o laptop.
        /// </summary>
        public static string AbrirPDFWebMessage {
            get {
                return ResourceManager.GetString("AbrirPDFWebMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa al módulo {0} desde un dispositivo móvil.
        /// </summary>
        public static string AccesoModuloMovilMessage {
            get {
                return ResourceManager.GetString("AccesoModuloMovilMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa al módulo {0} desde un pc o laptop.
        /// </summary>
        public static string AccesoModuloWebMessage {
            get {
                return ResourceManager.GetString("AccesoModuloWebMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar la sección {0} del documento {1} versión {2}.
        /// </summary>
        public static string ActualizarAccionMessage {
            get {
                return ResourceManager.GetString("ActualizarAccionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar anexo {4} al documento {1} versión {2} del módulo {0}.
        /// </summary>
        public static string AgregarAnexoDocumentoMessage {
            get {
                return ResourceManager.GetString("AgregarAnexoDocumentoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar anexo {4} al módulo {0}.
        /// </summary>
        public static string AgregarAnexoModuloMessage {
            get {
                return ResourceManager.GetString("AgregarAnexoModuloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprueba el documento {1} versión {2} del módulo {0}.
        /// </summary>
        public static string AprobarDocumentoMessage {
            get {
                return ResourceManager.GetString("AprobarDocumentoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string CaptionAccion {
            get {
                return ResourceManager.GetString("CaptionAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección IP.
        /// </summary>
        public static string CaptionDireccionIP {
            get {
                return ResourceManager.GetString("CaptionDireccionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Documento.
        /// </summary>
        public static string CaptionDocumento {
            get {
                return ResourceManager.GetString("CaptionDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la Empresa.
        /// </summary>
        public static string CaptionEmpresa {
            get {
                return ResourceManager.GetString("CaptionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string CaptionFechaRegistro {
            get {
                return ResourceManager.GetString("CaptionFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código del Registro.
        /// </summary>
        public static string CaptionId {
            get {
                return ResourceManager.GetString("CaptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string CaptionMensaje {
            get {
                return ResourceManager.GetString("CaptionMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negocios/Teconología.
        /// </summary>
        public static string CaptionNegocio {
            get {
                return ResourceManager.GetString("CaptionNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        public static string CaptionTipoDocumento {
            get {
                return ResourceManager.GetString("CaptionTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string CaptionUsuario {
            get {
                return ResourceManager.GetString("CaptionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifica el documento {1} versión {2} del módulo {0}.
        /// </summary>
        public static string CertificarDocumentoMessage {
            get {
                return ResourceManager.GetString("CertificarDocumentoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta control de cambios en el documento {1} versión {2} del módulo {0}.
        /// </summary>
        public static string ConsultarCambiosMessage {
            get {
                return ResourceManager.GetString("ConsultarCambiosMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar el documento {1} versión {2}.
        /// </summary>
        public static string EliminarAccionMessage {
            get {
                return ResourceManager.GetString("EliminarAccionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina anexo {4} del documento {1} versión {2} del módulo {0}.
        /// </summary>
        public static string EliminarAnexoDocumentoMessage {
            get {
                return ResourceManager.GetString("EliminarAnexoDocumentoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina anexo {4} del módulo {0}.
        /// </summary>
        public static string EliminarAnexoModuloMessage {
            get {
                return ResourceManager.GetString("EliminarAnexoModuloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar versión {5} del documento {1} versión {2} del módulo {0}.
        /// </summary>
        public static string GenerarCopiaDocumentoMessage {
            get {
                return ResourceManager.GetString("GenerarCopiaDocumentoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar PDF del documento {1} versión {2} en el módulo {0}.
        /// </summary>
        public static string GenerarPDFMessage {
            get {
                return ResourceManager.GetString("GenerarPDFMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar versión {2} del documento {1} en el módulo {0}.
        /// </summary>
        public static string GenerarVersionMessage {
            get {
                return ResourceManager.GetString("GenerarVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario conectado: {0}.
        /// </summary>
        public static string LoginAccionMessage {
            get {
                return ResourceManager.GetString("LoginAccionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desconectado: {0}.
        /// </summary>
        public static string LogOutAccionMessage {
            get {
                return ResourceManager.GetString("LogOutAccionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar la sección {0} del documento {1} versión {2}.
        /// </summary>
        public static string MostrarAccionMessage {
            get {
                return ResourceManager.GetString("MostrarAccionMessage", resourceCulture);
            }
        }
    }
}
