//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BCMWebPublic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BCMWebPublic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCMWeb.App_LocalResources.BCMWebPublic", typeof(BCMWebPublic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre BCMWeb.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string botReturnText {
            get {
                return ResourceManager.GetString("botReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso desde dispositivos móviles.
        /// </summary>
        public static string BSMMovilPageTitle {
            get {
                return ResourceManager.GetString("BSMMovilPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string captionButtonCancel {
            get {
                return ResourceManager.GetString("captionButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string captionButtonDelete {
            get {
                return ResourceManager.GetString("captionButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string captionButtonEdit {
            get {
                return ResourceManager.GetString("captionButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string captionButtonNew {
            get {
                return ResourceManager.GetString("captionButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string captionButtonSave {
            get {
                return ResourceManager.GetString("captionButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Políticas de Confidencialidad.
        /// </summary>
        public static string ConfidencialidadPageTitle {
            get {
                return ResourceManager.GetString("ConfidencialidadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Realmente desea eliminar el documento {0}?.
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        public static string ContactPageTitle {
            get {
                return ResourceManager.GetString("ContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas Frecuentes.
        /// </summary>
        public static string FAQPageTitle {
            get {
                return ResourceManager.GetString("FAQPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realice su selección....
        /// </summary>
        public static string itemSelectValue {
            get {
                return ResourceManager.GetString("itemSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manejador de Contenido para Continuidad de Negocios.
        /// </summary>
        public static string labelAppSlogan {
            get {
                return ResourceManager.GetString("labelAppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCMWeb.
        /// </summary>
        public static string labelAppTitle {
            get {
                return ResourceManager.GetString("labelAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando. Espere por favor....
        /// </summary>
        public static string labelLoadPanel {
            get {
                return ResourceManager.GetString("labelLoadPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso a la Aplicación.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedimientos de Continuidad.
        /// </summary>
        public static string ProcedimientoBCPPageTitle {
            get {
                return ResourceManager.GetString("ProcedimientoBCPPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis de Impacto.
        /// </summary>
        public static string ProcedimientoBIAPageTitle {
            get {
                return ResourceManager.GetString("ProcedimientoBIAPageTitle", resourceCulture);
            }
        }
    }
}
