//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCMWeb.App_LocalResources.ContactResource", typeof(ContactResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuela.
        /// </summary>
        public static string Direccion1Header {
            get {
                return ResourceManager.GetString("Direccion1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired C.A..
        /// </summary>
        public static string Direccion1Linea1 {
            get {
                return ResourceManager.GetString("Direccion1Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torre Morelos, Piso 4, oficina 4-B, Quebrada Honda, La Candelaria, 1010.
        /// </summary>
        public static string Direccion1Linea2 {
            get {
                return ResourceManager.GetString("Direccion1Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracas – Venezuela.
        /// </summary>
        public static string Direccion1Linea3 {
            get {
                return ResourceManager.GetString("Direccion1Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to España.
        /// </summary>
        public static string Direccion2Header {
            get {
                return ResourceManager.GetString("Direccion2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired C.A..
        /// </summary>
        public static string Direccion2Linea1 {
            get {
                return ResourceManager.GetString("Direccion2Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guillén de Castro, 26 – 28017..
        /// </summary>
        public static string Direccion2Linea2 {
            get {
                return ResourceManager.GetString("Direccion2Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madrid – España.
        /// </summary>
        public static string Direccion2Linea3 {
            get {
                return ResourceManager.GetString("Direccion2Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia.
        /// </summary>
        public static string Direccion3Header {
            get {
                return ResourceManager.GetString("Direccion3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired S.A.S.
        /// </summary>
        public static string Direccion3Linea1 {
            get {
                return ResourceManager.GetString("Direccion3Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrera 11B- # 98 - 08, oficina 202.
        /// </summary>
        public static string Direccion3Linea2 {
            get {
                return ResourceManager.GetString("Direccion3Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogotá – Colombia.
        /// </summary>
        public static string Direccion3Linea3 {
            get {
                return ResourceManager.GetString("Direccion3Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala.
        /// </summary>
        public static string Direccion4Header {
            get {
                return ResourceManager.GetString("Direccion4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Aplired S.A..
        /// </summary>
        public static string Direccion4Linea1 {
            get {
                return ResourceManager.GetString("Direccion4Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6ta Calle, 5 - 47, Zona 9, Edificio Vasil, 6to Nivel.
        /// </summary>
        public static string Direccion4Linea2 {
            get {
                return ResourceManager.GetString("Direccion4Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemala – Guatemala.
        /// </summary>
        public static string Direccion4Linea3 {
            get {
                return ResourceManager.GetString("Direccion4Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacto.BCMWeb@aplired.com.
        /// </summary>
        public static string EmailContacto {
            get {
                return ResourceManager.GetString("EmailContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico:.
        /// </summary>
        public static string labelEmailContacto {
            get {
                return ResourceManager.GetString("labelEmailContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes contactarnos a través de:.
        /// </summary>
        public static string SubHeader {
            get {
                return ResourceManager.GetString("SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nuestras oficinas ubicadas en:.
        /// </summary>
        public static string SubHeaderDireccion {
            get {
                return ResourceManager.GetString("SubHeaderDireccion", resourceCulture);
            }
        }
    }
}
