//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FichaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FichaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCMWeb.App_LocalResources.FichaResource", typeof(FichaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Entrevistado.
        /// </summary>
        public static string captionGrupo1 {
            get {
                return ResourceManager.GetString("captionGrupo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo:.
        /// </summary>
        public static string captionGrupo1Cargo {
            get {
                return ResourceManager.GetString("captionGrupo1Cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string captionGrupo1Email {
            get {
                return ResourceManager.GetString("captionGrupo1Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string captionGrupo1Nombre {
            get {
                return ResourceManager.GetString("captionGrupo1Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Organizativa.
        /// </summary>
        public static string captionGrupo1UO {
            get {
                return ResourceManager.GetString("captionGrupo1UO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la Entrevista.
        /// </summary>
        public static string captionGrupo2 {
            get {
                return ResourceManager.GetString("captionGrupo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobadores.
        /// </summary>
        public static string captionGrupo3 {
            get {
                return ResourceManager.GetString("captionGrupo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificadores.
        /// </summary>
        public static string captionGrupo4 {
            get {
                return ResourceManager.GetString("captionGrupo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas Claves.
        /// </summary>
        public static string captionGrupo5 {
            get {
                return ResourceManager.GetString("captionGrupo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesos.
        /// </summary>
        public static string captionGrupo6 {
            get {
                return ResourceManager.GetString("captionGrupo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere Certificación.
        /// </summary>
        public static string captionRequiereCertificacion {
            get {
                return ResourceManager.GetString("captionRequiereCertificacion", resourceCulture);
            }
        }
    }
}
