//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IniciativaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IniciativaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCMWeb.App_LocalResources.IniciativaResource", typeof(IniciativaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexos.
        /// </summary>
        public static string captionAnexos {
            get {
                return ResourceManager.GetString("captionAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Registro.
        /// </summary>
        public static string captionFechaRegistro {
            get {
                return ResourceManager.GetString("captionFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexar documento.
        /// </summary>
        public static string captionHeaderFormAnexos {
            get {
                return ResourceManager.GetString("captionHeaderFormAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización de Iniciativas.
        /// </summary>
        public static string captionHeaderFormIniciativas {
            get {
                return ResourceManager.GetString("captionHeaderFormIniciativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo.
        /// </summary>
        public static string captionIdAnexo {
            get {
                return ResourceManager.GetString("captionIdAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string captionNombreAnexo {
            get {
                return ResourceManager.GetString("captionNombreAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro. de Anexos.
        /// </summary>
        public static string captionNroAnexos {
            get {
                return ResourceManager.GetString("captionNroAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        public static string captionRutaAnexo {
            get {
                return ResourceManager.GetString("captionRutaAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un documento para cargar....
        /// </summary>
        public static string captionUploadBrowseButtonText {
            get {
                return ResourceManager.GetString("captionUploadBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string Estatus {
            get {
                return ResourceManager.GetString("Estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Cierre Estimada.
        /// </summary>
        public static string FechaCierreEstimada {
            get {
                return ResourceManager.GetString("FechaCierreEstimada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Cierre Real.
        /// </summary>
        public static string FechaCierreReal {
            get {
                return ResourceManager.GetString("FechaCierreReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio Estimada.
        /// </summary>
        public static string FechaInicioEstimada {
            get {
                return ResourceManager.GetString("FechaInicioEstimada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Inicio Real.
        /// </summary>
        public static string FechaInicioReal {
            get {
                return ResourceManager.GetString("FechaInicioReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación de Iniciativas.
        /// </summary>
        public static string GridTitle {
            get {
                return ResourceManager.GetString("GridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciativa.
        /// </summary>
        public static string IdIniciativa {
            get {
                return ResourceManager.GetString("IdIniciativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro. de Iniciativa.
        /// </summary>
        public static string NroIniciativa {
            get {
                return ResourceManager.GetString("NroIniciativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        public static string Observacion {
            get {
                return ResourceManager.GetString("Observacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto Estimado.
        /// </summary>
        public static string PresupuestoEstimado {
            get {
                return ResourceManager.GetString("PresupuestoEstimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto Real.
        /// </summary>
        public static string PresupuestoReal {
            get {
                return ResourceManager.GetString("PresupuestoReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string Responsable {
            get {
                return ResourceManager.GetString("Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string textoNormal {
            get {
                return ResourceManager.GetString("textoNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgente.
        /// </summary>
        public static string textoUrgente {
            get {
                return ResourceManager.GetString("textoUrgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Organizativa.
        /// </summary>
        public static string UnidadOrganizativa {
            get {
                return ResourceManager.GetString("UnidadOrganizativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgente.
        /// </summary>
        public static string Urgente {
            get {
                return ResourceManager.GetString("Urgente", resourceCulture);
            }
        }
    }
}
