//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReporteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReporteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCMWeb.App_LocalResources.ReporteResource", typeof(ReporteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string captionCantidad {
            get {
                return ResourceManager.GetString("captionCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala.
        /// </summary>
        public static string captionDescEscala {
            get {
                return ResourceManager.GetString("captionDescEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impacto Operacional.
        /// </summary>
        public static string captionImpactoOperacional {
            get {
                return ResourceManager.GetString("captionImpactoOperacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string captionM01 {
            get {
                return ResourceManager.GetString("captionM01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        public static string captionM02 {
            get {
                return ResourceManager.GetString("captionM02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string captionM03 {
            get {
                return ResourceManager.GetString("captionM03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string captionM04 {
            get {
                return ResourceManager.GetString("captionM04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string captionM05 {
            get {
                return ResourceManager.GetString("captionM05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string captionM06 {
            get {
                return ResourceManager.GetString("captionM06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string captionM07 {
            get {
                return ResourceManager.GetString("captionM07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string captionM08 {
            get {
                return ResourceManager.GetString("captionM08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        public static string captionM09 {
            get {
                return ResourceManager.GetString("captionM09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string captionM10 {
            get {
                return ResourceManager.GetString("captionM10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string captionM11 {
            get {
                return ResourceManager.GetString("captionM11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string captionM12 {
            get {
                return ResourceManager.GetString("captionM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMC.
        /// </summary>
        public static string captionMDTHeader {
            get {
                return ResourceManager.GetString("captionMDTHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso.
        /// </summary>
        public static string captionProceso {
            get {
                return ResourceManager.GetString("captionProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POR.
        /// </summary>
        public static string captionRPOHeader {
            get {
                return ResourceManager.GetString("captionRPOHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOR.
        /// </summary>
        public static string captionRTOHeader {
            get {
                return ResourceManager.GetString("captionRTOHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Organizativa.
        /// </summary>
        public static string captionUnidad {
            get {
                return ResourceManager.GetString("captionUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de Escala.
        /// </summary>
        public static string captionValorEscala {
            get {
                return ResourceManager.GetString("captionValorEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor de Impacto.
        /// </summary>
        public static string captionVIHeader {
            get {
                return ResourceManager.GetString("captionVIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRT.
        /// </summary>
        public static string captionWRTHeader {
            get {
                return ResourceManager.GetString("captionWRTHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir el gráfico.
        /// </summary>
        public static string ToolTipPrintButton {
            get {
                return ResourceManager.GetString("ToolTipPrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar el gráfico y guardar en su PC.
        /// </summary>
        public static string ToolTipSaveToDiskButton {
            get {
                return ResourceManager.GetString("ToolTipSaveToDiskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar el gráfico a una nueva ventana.
        /// </summary>
        public static string ToolTipSaveToWindowButton {
            get {
                return ResourceManager.GetString("ToolTipSaveToWindowButton", resourceCulture);
            }
        }
    }
}
