//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditoriaProcesoCritico
    {
        public long IdProceso { get; set; }
        public long IdAuditoriaProcesoCritico { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public bool EstadoAnterior { get; set; }
        public bool EstadoActual { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
