//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditoria
    {
        public long IdAuditoría { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Accion { get; set; }
        public string Mensaje { get; set; }
        public bool AplicaDocumento { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
