//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBCPRespuestaAccion
    {
        public long IdEmpresa { get; set; }
        public long IdDocumentoBCP { get; set; }
        public long IdBCPRespuestaAccion { get; set; }
        public long IdPersona { get; set; }
        public short NivelEscala { get; set; }
        public string NombreEscala { get; set; }
    
        public virtual tblBCPDocumento tblBCPDocumento { get; set; }
    }
}
