//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBIAProbabilidadRiesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBIAProbabilidadRiesgo()
        {
            this.tblBIAEventoRiesgo = new HashSet<tblBIAEventoRiesgo>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdProbabilidad { get; set; }
        public string Nombre { get; set; }
        public short Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIAEventoRiesgo> tblBIAEventoRiesgo { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
