//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBIAEventoRiesgo
    {
        public long IdEventoRiesgo { get; set; }
        public long IdEmpresa { get; set; }
        public long Probabilidad { get; set; }
        public long Impacto { get; set; }
        public long Control { get; set; }
        public long Severidad { get; set; }
        public long IdEstadoRiesgo { get; set; }
        public long IdFuenteRiesgo { get; set; }
    
        public virtual tblBIAControlRiesgo tblBIAControlRiesgo { get; set; }
        public virtual tblBIAFuenteRiesgo tblBIAFuenteRiesgo { get; set; }
        public virtual tblImpactoRiesgo tblImpactoRiesgo { get; set; }
        public virtual tblBIAProbabilidadRiesgo tblBIAProbabilidadRiesgo { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
