//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBIADocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBIADocumento()
        {
            this.tblBIAComentario = new HashSet<tblBIAComentario>();
            this.tblBIAImpactoFinanciero = new HashSet<tblBIAImpactoFinanciero>();
            this.tblBIAProceso = new HashSet<tblBIAProceso>();
            this.tblDocumento = new HashSet<tblDocumento>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdDocumento { get; set; }
        public long IdUnidadOrganizativa { get; set; }
        public Nullable<long> IdCadenaServicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIAComentario> tblBIAComentario { get; set; }
        public virtual tblUnidadOrganizativa tblUnidadOrganizativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIAImpactoFinanciero> tblBIAImpactoFinanciero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIAProceso> tblBIAProceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumento> tblDocumento { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
