//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBIAGranImpacto
    {
        public long IdEmpresa { get; set; }
        public long IdDocumentoBIA { get; set; }
        public long IdProceso { get; set; }
        public long IdGranImpacto { get; set; }
        public int IdMes { get; set; }
        public string Observacion { get; set; }
        public string Explicacion { get; set; }
    
        public virtual tblBIAProceso tblBIAProceso { get; set; }
        public virtual tblMes tblMes { get; set; }
    }
}
