//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDispositivo1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDispositivo1()
        {
            this.tblDispositivoEnvio1 = new HashSet<tblDispositivoEnvio1>();
            this.tblDispositivoConexion1 = new HashSet<tblDispositivoConexion1>();
        }
    
        public long IdDispositivo { get; set; }
        public long IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string IMEI_Dispositivo { get; set; }
        public string NombreDispositivo { get; set; }
        public string Fabricante { get; set; }
        public string Modelo { get; set; }
        public string Plataforma { get; set; }
        public string Version { get; set; }
        public string TipoDispositivo { get; set; }
        public string TokenDispositivo { get; set; }
    
        public virtual tblUsuario tblUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDispositivoEnvio1> tblDispositivoEnvio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDispositivoConexion1> tblDispositivoConexion1 { get; set; }
    }
}
