//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentoContenido
    {
        public long IdEmpresa { get; set; }
        public long IdDocumento { get; set; }
        public long IdTipoDocumento { get; set; }
        public long IdSubModulo { get; set; }
        public byte[] ContenidoBin { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
        public virtual tblModulo tblModulo { get; set; }
    }
}
