//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpresaUsuario
    {
        public long IdEmpresa { get; set; }
        public long IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public long IdNivelUsuario { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblNivelUsuario tblNivelUsuario { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
