//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIniciativas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIniciativas()
        {
            this.tblIniciativas_Anexo = new HashSet<tblIniciativas_Anexo>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdIniciativa { get; set; }
        public Nullable<int> NroIniciativa { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdUnidadOrganizativa { get; set; }
        public string NombreResponsable { get; set; }
        public Nullable<System.DateTime> FechaInicioEstimada { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<System.DateTime> FechaCierreEstimada { get; set; }
        public Nullable<System.DateTime> FechaCierreReal { get; set; }
        public Nullable<decimal> PresupuestoEstimado { get; set; }
        public Nullable<decimal> PresupuestoReal { get; set; }
        public Nullable<short> IdEstatusIniciativa { get; set; }
        public Nullable<bool> Urgente { get; set; }
        public string Observacion { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblPlanTrabajoEstatus tblPlanTrabajoEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIniciativas_Anexo> tblIniciativas_Anexo { get; set; }
    }
}
