//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMTMensajeActualizacion
    {
        public long IdEmpresa { get; set; }
        public long IdMensaje { get; set; }
        public long IdModulo { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime FechaUltimoEnvio { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblModulo tblModulo { get; set; }
    }
}
