//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMTResponsableUpdate_Correo
    {
        public long IdEmpresa { get; set; }
        public long IdModulo { get; set; }
        public long IdMensaje { get; set; }
        public long IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual tblPMTResponsableUpdate tblPMTResponsableUpdate { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
