//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlanTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlanTrabajo()
        {
            this.tblPlanTrabajoAuditoria = new HashSet<tblPlanTrabajoAuditoria>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdAccion { get; set; }
        public long IdActividad { get; set; }
        public string Recomendacion { get; set; }
        public string Responsable { get; set; }
        public System.DateTime FechaPropuestaEjecucion { get; set; }
        public short Ejecutada { get; set; }
        public Nullable<long> IdActividadPadre { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblPlanTrabajoAccion tblPlanTrabajoAccion { get; set; }
        public virtual tblPlanTrabajoEstatus tblPlanTrabajoEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlanTrabajoAuditoria> tblPlanTrabajoAuditoria { get; set; }
    }
}
