//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlanTrabajoEstatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlanTrabajoEstatus()
        {
            this.tblCultura_PlanTrabajoEstatus = new HashSet<tblCultura_PlanTrabajoEstatus>();
            this.tblPlanTrabajo = new HashSet<tblPlanTrabajo>();
            this.tblPlanTrabajoAuditoria = new HashSet<tblPlanTrabajoAuditoria>();
            this.tblIniciativas = new HashSet<tblIniciativas>();
        }
    
        public short IdEstatusActividad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCultura_PlanTrabajoEstatus> tblCultura_PlanTrabajoEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlanTrabajo> tblPlanTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlanTrabajoAuditoria> tblPlanTrabajoAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIniciativas> tblIniciativas { get; set; }
    }
}
