//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaEjecucionParticipanteTelefono
    {
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public long IdEjercicio { get; set; }
        public long IdParticipante { get; set; }
        public long IdTelefono { get; set; }
        public int CodigoArea { get; set; }
        public int NroTelefono { get; set; }
        public int Extension1 { get; set; }
        public int Extension2 { get; set; }
    
        public virtual tblPBEPruebaEjecucionParticipante tblPBEPruebaEjecucionParticipante { get; set; }
    }
}
