//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMTProgramacionUsuario
    {
        public long IdPMTProgramacion { get; set; }
        public long IdUsuario { get; set; }
        public Nullable<short> IdTipoNotificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaNotificacion { get; set; }
    
        public virtual tblPMTProgramacionTipoNotificacion tblPMTProgramacionTipoNotificacion { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblPMTProgramacion tblPMTProgramacion { get; set; }
    }
}
