//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaEjecucionParticipanteTelefono
    {
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public long IdEjercicio { get; set; }
        public long IdParticipante { get; set; }
        public long IdTelefono { get; set; }
        public int CodigoArea { get; set; }
        public int NroTelefono { get; set; }
        public int Extension1 { get; set; }
        public int Extension2 { get; set; }
    
        public virtual tblPBEPruebaEjecucionParticipante tblPBEPruebaEjecucionParticipante { get; set; }
    }
}
