//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaPlanificacionParticipanteCorreo
    {
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public long IdParticipante { get; set; }
        public long IdCorreo { get; set; }
        public string Correo { get; set; }
    
        public virtual tblPBEPruebaPlanificacionParticipante tblPBEPruebaPlanificacionParticipante { get; set; }
    }
}
