//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaPlanificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPBEPruebaPlanificacion()
        {
            this.tblPBEPruebaEjecucionEjercicio = new HashSet<tblPBEPruebaEjecucionEjercicio>();
            this.tblPBEPruebaPlanificacionEjercicio = new HashSet<tblPBEPruebaPlanificacionEjercicio>();
            this.tblPBEPruebaPlanificacionParticipante = new HashSet<tblPBEPruebaPlanificacionParticipante>();
            this.tblPBEPruebaPlanificacionRecurso = new HashSet<tblPBEPruebaPlanificacionRecurso>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public string Prueba { get; set; }
        public string Propósito { get; set; }
        public System.DateTime FechaPlanificacion { get; set; }
        public string Lugar { get; set; }
        public long IdResponsable { get; set; }
        public short IdEstatus { get; set; }
        public bool Negocios { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionEjercicio> tblPBEPruebaEjecucionEjercicio { get; set; }
        public virtual tblPersona tblPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaPlanificacionEjercicio> tblPBEPruebaPlanificacionEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaPlanificacionParticipante> tblPBEPruebaPlanificacionParticipante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaPlanificacionRecurso> tblPBEPruebaPlanificacionRecurso { get; set; }
    }
}
