//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaEjecucionParticipante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPBEPruebaEjecucionParticipante()
        {
            this.tblPBEPruebaEjecucionParticipanteCorreo = new HashSet<tblPBEPruebaEjecucionParticipanteCorreo>();
            this.tblPBEPruebaEjecucionParticipanteTelefono = new HashSet<tblPBEPruebaEjecucionParticipanteTelefono>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public long IdEjercicio { get; set; }
        public long IdParticipante { get; set; }
        public string Empresa { get; set; }
        public string Nombre { get; set; }
    
        public virtual tblPBEPruebaEjecucionEjercicio tblPBEPruebaEjecucionEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionParticipanteCorreo> tblPBEPruebaEjecucionParticipanteCorreo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionParticipanteTelefono> tblPBEPruebaEjecucionParticipanteTelefono { get; set; }
    }
}
