//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMTProgramacion
    {
        public long IdPMTProgramación { get; set; }
        public long IdEmpresa { get; set; }
        public long IdDocumento { get; set; }
        public long IdModulo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public long IdEstado { get; set; }
        public bool Negocios { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
