//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaEjecucionEjercicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPBEPruebaEjecucionEjercicio()
        {
            this.tblPBEPruebaEjecucionEjercicioParticipante = new HashSet<tblPBEPruebaEjecucionEjercicioParticipante>();
            this.tblPBEPruebaEjecucionEjercicioRecurso = new HashSet<tblPBEPruebaEjecucionEjercicioRecurso>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public long IdEjercicio { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<short> IdEstatus { get; set; }
        public long IdEjercicioPlanificacion { get; set; }
        public int DuracionHoras { get; set; }
        public int DuracionMinutos { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblPBEPruebaEjecucion tblPBEPruebaEjecucion { get; set; }
        public virtual tblPBEPruebaEstatus tblPBEPruebaEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionEjercicioParticipante> tblPBEPruebaEjecucionEjercicioParticipante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionEjercicioRecurso> tblPBEPruebaEjecucionEjercicioRecurso { get; set; }
    }
}
