//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPersona()
        {
            this.tblBCPReanudacionPersonaClave = new HashSet<tblBCPReanudacionPersonaClave>();
            this.tblBCPRecuperacionPersonaClave = new HashSet<tblBCPRecuperacionPersonaClave>();
            this.tblBIAPersonaRespaldoProceso = new HashSet<tblBIAPersonaRespaldoProceso>();
            this.tblDocumentoAprobacion = new HashSet<tblDocumentoAprobacion>();
            this.tblDocumentoCertificacion = new HashSet<tblDocumentoCertificacion>();
            this.tblDocumentoPersonaClave = new HashSet<tblDocumentoPersonaClave>();
            this.tblPersonaDireccion = new HashSet<tblPersonaDireccion>();
            this.tblPersonaTelefono = new HashSet<tblPersonaTelefono>();
            this.tblPersonaCorreo = new HashSet<tblPersonaCorreo>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdPersona { get; set; }
        public string Nombre { get; set; }
        public string Identificacion { get; set; }
        public Nullable<long> IdUnidadOrganizativa { get; set; }
        public Nullable<long> IdCargo { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBCPReanudacionPersonaClave> tblBCPReanudacionPersonaClave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBCPRecuperacionPersonaClave> tblBCPRecuperacionPersonaClave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBIAPersonaRespaldoProceso> tblBIAPersonaRespaldoProceso { get; set; }
        public virtual tblCargo tblCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentoAprobacion> tblDocumentoAprobacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentoCertificacion> tblDocumentoCertificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentoPersonaClave> tblDocumentoPersonaClave { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonaDireccion> tblPersonaDireccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonaTelefono> tblPersonaTelefono { get; set; }
        public virtual tblUnidadOrganizativa tblUnidadOrganizativa { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonaCorreo> tblPersonaCorreo { get; set; }
    }
}
