//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMTProgramacionAuditoria
    {
        public long IdEmpresa { get; set; }
        public long IdModulo { get; set; }
        public long IdDocumento { get; set; }
        public System.DateTime FechaInicioActualizacion { get; set; }
        public System.DateTime FechaUltimaActualizacion { get; set; }
        public long IdUsuarioActuailiza { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
    }
}
