//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMTFrecuencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPMTFrecuencia()
        {
            this.tblPMTFrecuenciaParticipante = new HashSet<tblPMTFrecuenciaParticipante>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdDocumento { get; set; }
        public long IdTipoDocumento { get; set; }
        public long IdFrecuencia { get; set; }
        public short IdTipoFrecuencia { get; set; }
        public string TipoFrecuencia { get; set; }
        public string Segmento { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPMTFrecuenciaParticipante> tblPMTFrecuenciaParticipante { get; set; }
    }
}
