//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaEjecucionEjercicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPBEPruebaEjecucionEjercicio()
        {
            this.tblPBEPruebaEjecucionParticipante = new HashSet<tblPBEPruebaEjecucionParticipante>();
            this.tblPBEPruebaEjecucionRecurso = new HashSet<tblPBEPruebaEjecucionRecurso>();
            this.tblPBEPruebaEjecucionResultado = new HashSet<tblPBEPruebaEjecucionResultado>();
        }
    
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public long IdEjercicio { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinalizacion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdResponsable { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblPBEPruebaPlanificacion tblPBEPruebaPlanificacion { get; set; }
        public virtual tblPersona tblPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionParticipante> tblPBEPruebaEjecucionParticipante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionRecurso> tblPBEPruebaEjecucionRecurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPBEPruebaEjecucionResultado> tblPBEPruebaEjecucionResultado { get; set; }
    }
}
