//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentoAnexo
    {
        public long IdEmpresa { get; set; }
        public long IdDocumento { get; set; }
        public long IdTipoDocumento { get; set; }
        public long IdAnexo { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> IsFolder { get; set; }
        public byte[] Data { get; set; }
        public Nullable<System.DateTime> LastWriteTime { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
    }
}
