//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIniciativas
    {
        public long IdEmpresa { get; set; }
        public long IdIniciativa { get; set; }
        public Nullable<int> NroIniciativa { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdUnidadOrganizativa { get; set; }
        public string UnidadOrganizativa { get; set; }
        public string NombreResponsable { get; set; }
        public Nullable<System.DateTime> FechaInicioEstimada { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<System.DateTime> FechaCierreEstimada { get; set; }
        public Nullable<System.DateTime> FechaCierreReal { get; set; }
        public Nullable<decimal> PresupuestoEstimado { get; set; }
        public Nullable<decimal> PresupuestoReal { get; set; }
        public Nullable<short> IdEstatusIniciativa { get; set; }
        public string Observacion { get; set; }
        public Nullable<short> IdPrioridad { get; set; }
        public Nullable<decimal> MontoAbonado { get; set; }
        public Nullable<decimal> MontoPendiente { get; set; }
        public Nullable<decimal> PorcentajeAvance { get; set; }
        public Nullable<int> HorasEstimadas { get; set; }
        public Nullable<int> HorasConsumidas { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblIniciativaPrioridad tblIniciativaPrioridad { get; set; }
        public virtual tblPlanTrabajoEstatus tblPlanTrabajoEstatus { get; set; }
    }
}
