//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPBEPruebaEjecucionResultado
    {
        public long IdEmpresa { get; set; }
        public long IdPlanificacion { get; set; }
        public long IdContenido { get; set; }
        public byte[] Contenido { get; set; }
    
        public virtual tblPBEPruebaEjecucion tblPBEPruebaEjecucion { get; set; }
    }
}
