//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMTProgramacionTipoActualizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPMTProgramacionTipoActualizacion()
        {
            this.tblCultura_PMTProgramacionTipoActualizacion = new HashSet<tblCultura_PMTProgramacionTipoActualizacion>();
            this.tblPMTProgramacion = new HashSet<tblPMTProgramacion>();
        }
    
        public short IdTipoActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCultura_PMTProgramacionTipoActualizacion> tblCultura_PMTProgramacionTipoActualizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPMTProgramacion> tblPMTProgramacion { get; set; }
    }
}
