//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditoria
    {
        public long IdAuditoria { get; set; }
        public Nullable<long> IdEmpresa { get; set; }
        public Nullable<long> IdDocumento { get; set; }
        public Nullable<long> IdTipoDocumento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string DireccionIP { get; set; }
        public string Mensaje { get; set; }
        public string Accion { get; set; }
        public Nullable<long> IdUsuario { get; set; }
        public bool Negocios { get; set; }
        public string DatosModificados { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
