//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMWeb.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCriticidad
    {
        public System.DateTime FechaAplicacion { get; set; }
        public long IdEmpresa { get; set; }
        public long IdTipoEscala { get; set; }
        public string DescripcionEscala { get; set; }
    
        public virtual tblEmpresa tblEmpresa { get; set; }
        public virtual tblTipoEscala tblTipoEscala { get; set; }
    }
}
